spring.application.name=demo


# Chave do TMDB (não compartilhe!)
# substitua o valor abaixo pela sua chave obtida em https://www.themoviedb.org/settings/api
# se ficar em branco ou inválido, os endpoints retornarão 400/500 e você verá a mensagem de erro no frontend

#EXEMPLO: tmdb.api.key=1a2b3c4d5e6f...
tmdb.api.key=adb83e328450881088bd8b29a43badd8
